# Using https://github.com/tox-dev/azure-pipelines-template
# and learned from https://github.com/wasp/waspy/blob/master/azure-pipelines.yml

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
resources:
  repositories:
    - repository: tox
      type: github
      endpoint: github
      name: tox-dev/azure-pipelines-template

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - cyberbrain/*
      - cyberbrain-vsc/*
      - test/*
      - azure-pipelines.yml

pr:
  branches:
    include:
      - '*'
  paths:
    # Ideally we should trigger different checks based on modified sources.
    # For example, ignore Python tests if only js files are modified.
    # There's a hacky way: https://stackoverflow.com/a/59608109/2142577
    # Unless Azure pipelines provide a builtin way, I think it's not worth it.
    include:
      - cyberbrain/*
      - cyberbrain-vsc/*
      - test/*
      - azure-pipelines.yml

variables:
  PYTEST_ADDOPTS: "-v -v -ra --showlocals"
  PYTEST_XDIST_PROC_NR: 'auto'
  CI_RUN: 'yes'

jobs:
  - template: run-tox-env.yml@tox
    parameters:
      jobs:
        py37:
          image: [ linux, windows, macOs ]
        py38:
          image: [ linux, windows, macOs ]
        py39:
          image: [ linux, windows, macOs ]

  - job: ts_js_lint
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.18.3'
        displayName: 'Install Node.js'

      - script: npm install && npm install acorn
        workingDirectory: 'cyberbrain-vsc'
        displayName: 'NPM Install'

      - task: Npm@1
        inputs:
          command: custom
          customCommand: 'run lint'
          workingDir: 'cyberbrain-vsc'
        displayName: Run Lint

  - job: python_lint
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
      - script: python3.9 -m pip install black
      - script: black --check cyberbrain test
